[package]
name = "slsg"
description = "Scriptable Lua Site Generator"
version = "0.3.0"
license = "GPL-3.0-only"
repository = "https://github.com/Dimev/slsg"
keywords = ["lua", "website", "html", "blog", "markdown"]
categories = ["web-programming", "template-engine", "command-line-utilities"]
edition = "2021"

[dependencies]
crossterm = "0.28.1"
latex2mathml = "0.2.3"
lazy_static = "1.5.0"
mlua = { version = "0.10.0", features = ["luajit"] }
notify = { version = "8.0.0", default-features = false, features = ["macos_kqueue"] }
pico-args = "0.5.0"
rsass = "0.29.0"
syntect = "5.2.0"
unicode-width = "0.2.0"
winnow = "0.7.6"
