[package]
name = "slsg"
description = "Scriptable Lua Site Generator"
version = "0.2.0"
license = "GPL-3.0-only"
repository = "https://github.com/Dimev/slsg"
keywords = ["lua", "website", "html", "javascript"]
categories = ["web-programming", "template-engine", "command-line-utilities"]
edition = "2021"

[dependencies]
crossterm = "0.28.1"
latex2mathml = "0.2.3"
mlua = { version = "0.10.0", features = ["lua54"] }
notify = { version = "7.0.0", default-features = false, features = ["macos_kqueue"] }
pico-args = "0.5.0"
regex = "1.11.1"
rsass = "0.28.10"
unicode-width = "0.2.0"
