[package]
name = "slsg"
description = "Scriptable Lua Site Generator"
version = "0.1.0"
license = "GPL-3.0-only"
repository = "https://github.com/Dimev/slsg"
keywords = ["lua", "website", "html", "javascript"]
categories = ["web-programming", "template-engine", "command-line-utilities"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.79"
clap = { version = "4.4.18", features = ["derive"] }
crossterm = "0.27.0"
mlua = { version = "0.9.5", features = ["lua54", "serialize"] }
notify-debouncer-mini = "0.4.1"
latex2mathml = "0.2.3"
fancy-regex = "0.13.0"
image = "0.25.1"
grass = { version = "0.13.2", default-features = false }
